name: React TypeScript CI

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build and Security Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Security audit
      run: npm audit
      continue-on-error: false
    
    - name: Build
      run: npm run build
      env:
        CI: false # This ignores warnings during build